services:
  k0s:
    container_name: k0s-development
    hostname: k0s-development
    # Bind to different local IP address
    ports:
      - 127.0.0.1:80:8080
      - 127.0.0.1:443:8443
      - 127.0.0.1:7443:6443
    restart: no
